[package]
name = "prediction"
version = "0.1.0"
authors = ["Keyne"]
edition = "2021"

[dependencies]
cosmwasm-schema     = { workspace = true }
cosmwasm-std        = { workspace = true }
cw-storage-plus     = { workspace = true }
schemars            = { workspace = true }
serde               = { workspace = true }
thiserror           = { workspace = true }
pyth-sdk-cw         = { workspace = true }
